######################################################################
# Automatically generated by qmake (2.00a) Wed May 4 15:30:40 2005
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
SOURCES += layouts.cpp
CONFIG += qt warn_on debug  create_prl link_prl
OBJECTS_DIR=.obj/debug-shared
MOC_DIR=.moc/debug-shared
