######################################################################
# Automatically generated by qmake (2.00a) Sun Jun 26 15:25:59 2005
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
SOURCES += picture.cpp
OBJECTS_DIR=.obj/debug-shared
MOC_DIR=.moc/debug-shared
CONFIG += qt warn_on debug  create_prl link_prl
