######################################################################
# Automatically generated by qmake (2.00a) Wed May 3 11:08:01 2006
######################################################################

TEMPLATE = app
TARGET += 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
