######################################################################
# Automatically generated by qmake (2.00a) Tue Apr 11 12:09:28 2006
######################################################################

TEMPLATE = app
TARGET += 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
