/*
 * This file was generated by dbusxml2cpp version 0.6
 * Command line was: dbusxml2cpp -c CarAdaptor -a car_adaptor_p.h:car_adaptor.cpp car.xml
 *
 * dbusxml2cpp is Copyright (C) 2006 Trolltech ASA. All rights reserved.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "car_adaptor_p.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class CarAdaptor
 */

CarAdaptor::CarAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

CarAdaptor::~CarAdaptor()
{
    // destructor
}

void CarAdaptor::accelerate()
{
    // handle method call com.trolltech.Examples.CarInterface.accelerate
    QMetaObject::invokeMethod(parent(), "accelerate");
}

void CarAdaptor::decelerate()
{
    // handle method call com.trolltech.Examples.CarInterface.decelerate
    QMetaObject::invokeMethod(parent(), "decelerate");
}

void CarAdaptor::turnLeft()
{
    // handle method call com.trolltech.Examples.CarInterface.turnLeft
    QMetaObject::invokeMethod(parent(), "turnLeft");
}

void CarAdaptor::turnRight()
{
    // handle method call com.trolltech.Examples.CarInterface.turnRight
    QMetaObject::invokeMethod(parent(), "turnRight");
}

