#!/bin/sh

sed -i "s/\#isdl //g" $1
sed -i "s/isourloc/$2/g" $1

if [ "$1" = ./winbuild/menu.lst ]
then
sed -i 's/\; isdl //g' ./winbuild/unetbootin.nsi
sed -i "s/isourloc/$2/g" ./winbuild/unetbootin.nsi
fi
