#!/bin/sh

sed -i "s/\#rptl //g" $1
sed -i "s/rpubnkernurl/$2/g" $1
sed -i "s/rpubniniturl/$3/g" $1

if [ "$1" = ./winbuild/menu.lst ]
then
sed -i 's/\; ltbe //g' ./winbuild/unetbootin.nsi
sed -i "s/rpubnkernurl/$2/g" ./winbuild/unetbootin.nsi
sed -i "s/rpubniniturl/$3/g" ./winbuild/unetbootin.nsi
fi
