#!/bin/sh

sed -i "s/initrd \/boot\/ubninit//g" $1
sed -i "s/initrd \$grbootsup\/ubninit//g" $1
sed -i "s/initrd \/wubi\/boot\/ubninit//g" $1
sed -i "s/initrd \/ubuntu\/disks\/boot\/ubninit//g" $1
sed -i "s/cat \/boot\/ubninit/echo something/g" $1
sed -i "s/cat \$targetdir\/boot\/ubninit/echo something/g" $1
