######################################################################
# Automatically generated by qmake (2.00a) Mon Apr 10 11:16:20 2006
######################################################################

TEMPLATE = app
TARGET += 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
