######################################################################
# Automatically generated by qmake (2.00a) Tue May 2 15:31:16 2006
######################################################################

TEMPLATE = app
TARGET += 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
