######################################################################
# Automatically generated by qmake (2.00a) Thu Apr 20 16:22:46 2006
######################################################################

TEMPLATE = app
TARGET += 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
