/*
 * This file was generated by dbusxml2cpp version 0.6
 * Command line was: dbusxml2cpp -a chat_adaptor.h: com.trolltech.chat.xml
 *
 * dbusxml2cpp is Copyright (C) 2006 Trolltech ASA. All rights reserved.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef CHAT_ADAPTOR_H_142741156243605
#define CHAT_ADAPTOR_H_142741156243605

#include <QtCore/QObject>
#include <QtDBus/QtDBus>

QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface com.trolltech.chat
 */
class ChatAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "com.trolltech.chat")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"com.trolltech.chat\" >\n"
"    <signal name=\"message\" >\n"
"      <arg direction=\"out\" type=\"s\" name=\"nickname\" />\n"
"      <arg direction=\"out\" type=\"s\" name=\"text\" />\n"
"    </signal>\n"
"    <signal name=\"action\" >\n"
"      <arg direction=\"out\" type=\"s\" name=\"nickname\" />\n"
"      <arg direction=\"out\" type=\"s\" name=\"text\" />\n"
"    </signal>\n"
"  </interface>\n"
        "")
public:
    ChatAdaptor(QObject *parent);
    virtual ~ChatAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
Q_SIGNALS: // SIGNALS
    void action(const QString &nickname, const QString &text);
    void message(const QString &nickname, const QString &text);
};

#endif
