######################################################################
# Automatically generated by qmake (2.00a) Thu Apr 6 10:47:18 2006
######################################################################

TEMPLATE = app
TARGET += 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
