#!/bin/sh

if [ "$(echo $0 | grep x64)" != "" ]
then
arch=x86_64
else
arch=i386
fi

fninstmesage="*IMPORTANT* After rebooting, ignore any error messages and select back if prompted for a CD, then go to the main menu, select the 'Start Installation' option, choose 'Network' as the source, choose 'HTTP' as the protocol, enter 'mirrors.kernel.org' when prompted for a server, and enter '\/centos\/5.1\/os\/$arch' when asked for the folder."

./functions/kernpar $1 'splash=silent showopts'
./functions/finmes $1 "$fninstmesage"
