#!/bin/sh

sed -i "s/kernel \/boot\/ubnkern/kernel \/boot\/ubnkern ramdisk_size=100000 init=\/etc\/init lang=us apm=power-off vga=791 nomce noapic quiet BOOT_IMAGE=knoppix/g" $1
sed -i "s/kernel \/wubi\/boot\/ubnkern/kernel \/wubi\/boot\/ubnkern ramdisk_size=100000 init=\/etc\/init lang=us apm=power-off vga=791 nomce noapic quiet BOOT_IMAGE=knoppix/g" $1
sed -i "s/kernel \/ubuntu\/disks\/boot\/ubnkern/kernel \/ubuntu\/disks\/boot\/ubnkern ramdisk_size=100000 init=\/etc\/init lang=us apm=power-off vga=791 nomce noapic quiet BOOT_IMAGE=knoppix/g" $1
