#!/bin/sh

if [ "$(echo $0 | grep x64)" != "" ]
then
arch=amd64
else
arch=i386
fi

if [ "$(echo $0 | grep stable )" != "" ]
then
debdistrel=stable
fi

if [ "$(echo $0 | grep testing )" != "" ]
then
debdistrel=testing
fi

if [ "$(echo $0 | grep unstable )" != "" ]
then
debdistrel=unstable
fi

kerndlurl="http:\/\/ftp.debian.org\/debian\/dists\/$debdistrel\/main\/installer-$arch\/current\/images\/netboot\/gtk\/debian-installer\/$arch\/linux"
initdlurl="http:\/\/ftp.debian.org\/debian\/dists\/$debdistrel\/main\/installer-$arch\/current\/images\/netboot\/gtk\/debian-installer\/$arch\/initrd.gz"

./functions/kernpar $1 'video=vesa:ywrap,mtrr vga=788 installgui'
./functions/nckern $1
./functions/ncinit $1
./functions/netbt $1 "$kerndlurl" "$initdlurl"
