#!/bin/sh

if [ "$(echo $0 | grep x64)" != "" ]
then
arch=x86_64
else
arch=i386
fi

kerndlurl="http:\/\/download.fedora.redhat.com\/pub\/fedora\/linux\/development\/$arch\/os\/images\/pxeboot\/vmlinuz"
initdlurl="http:\/\/download.fedora.redhat.com\/pub\/fedora\/linux\/development\/$arch\/os\/images\/pxeboot\/initrd.img"
fninstmesage="*IMPORTANT* After rebooting, ignore any error messages and select back if prompted for a CD, then go to the main menu, select the 'Start Installation' option, choose 'Network' as the source, choose 'HTTP' as the protocol, enter 'download.fedora.redhat.com' when prompted for a server, and enter '\/pub\/fedora\/linux\/development\/$arch\/os' when asked for the folder."

./functions/kernpar $1 'splash=silent showopts'
./functions/finmes $1 "$fninstmesage"
./functions/nckern $1
./functions/ncinit $1
./functions/netbt $1 "$kerndlurl" "$initdlurl"
