#!/bin/sh

sed -i "s/kernel \/boot\/ubnkern/kernel \/boot\/ubnkern splash=silent showopts/g" $1
sed -i "s/kernel \/wubi\/boot\/ubnkern/kernel \/wubi\/boot\/ubnkern splash=silent showopts/g" $1

if [ "$(echo $0 | grep x64)" != "" ]
then
arch=x86_64
else
arch=i386
fi

kerndlurl="http:\/\/download.opensuse.org\/distribution\/SL-OSS-factory\/inst-source\/boot\/$arch\/loader\/linux"
initdlurl="http:\/\/download.opensuse.org\/distribution\/SL-OSS-factory\/inst-source\/boot\/$arch\/loader\/initrd"
fninstmesage="After rebooting, "

sed -i "s/\#rptl //g" $1
sed -i "s/rpubnkernurl/$kerndlurl/g" $1
sed -i "s/rpubniniturl/$initdlurl/g" $1

sed -i "s/cp \.\/ubnkern/\#/g" $1
sed -i "s/cp \.\/ubninit/\#/g" $1

sed -i s/afterinstmessage=""/afterinstmessage="$fninstmesage"/g $1

if [ "$1" = ./winbuild/menu.lst ]
then
sed -i 's/File "ubnkern"//g' ./winbuild/unetbootin.nsi
sed -i 's/File "ubninit"//g' ./winbuild/unetbootin.nsi
sed -i 's/\; ltbe //g' ./winbuild/unetbootin.nsi
sed -i "s/rpubnkernurl/$kerndlurl/g" ./winbuild/unetbootin.nsi
sed -i "s/rpubniniturl/$initdlurl/g" ./winbuild/unetbootin.nsi
sed -i "s/You need to reboot to complete the installation\./You need to reboot to complete the installation\. $fninstmesage/g" ./winbuild/unetbootin.nsi
fi
