#!/bin/sh

sed -i "s/kernel \/boot\/ubninit/kernel \/boot\/ubninit root=\/dev\/ram0 init=\/linuxrc ramdisk_size=100000 skip xvesa toram/g" $1
sed -i "s/kernel \/wubi\/boot\/ubninit/kernel \/wubi\/boot\/ubninit root=\/dev\/ram0 init=\/linuxrc ramdisk_size=100000 skip xvesa toram/g" $1
