#!/bin/sh

if [ "$(echo $0 | grep x64)" != "" ]
then
arch=amd64
else
arch=i386
fi

kerndlurl="http:\/\/archive.ubuntu.com\/ubuntu\/dists\/hardy\/main\/installer-$arch\/current\/images\/netboot\/ubuntu-installer\/$arch\/linux"
initdlurl="http:\/\/archive.ubuntu.com\/ubuntu\/dists\/hardy\/main\/installer-$arch\/current\/images\/netboot\/ubuntu-installer\/$arch\/initrd.gz"

./functions/kernpar $1 'vga=normal'
./functions/nckern $1
./functions/ncinit $1
./functions/netbt $1 "$kerndlurl" "$initdlurl"
