#!/bin/sh

if [ "$(echo $0 | grep x64)" != "" ]
then
arch=amd64
else
arch=i386
fi

sed -i "s/kernel \/boot\/ubnkern/kernel \/boot\/ubnkern vga=normal/g" $1
sed -i "s/kernel \/wubi\/boot\/ubnkern/kernel \/wubi\/boot\/ubnkern vga=normal/g" $1

sed -i "s/\#rptl //g" $1
sed -i "s/rpubnkernurl/ftp:\/\/ftp.ubuntu.com\/ubuntu\/dists\/hardy\/main\/installer-$arch\/current\/images\/netboot\/ubuntu-installer\/$arch\/linux/g" $1
sed -i "s/rpubniniturl/ftp:\/\/ftp.ubuntu.com\/ubuntu\/dists\/hardy\/main\/installer-$arch\/current\/images\/netboot\/ubuntu-installer\/$arch\/initrd.gz/g" $1

sed -i "s/cp \.\/ubnkern/\#/g" $1
sed -i "s/cp \.\/ubninit/\#/g" $1
