#!/bin/sh

sed -i "s/kernel \/boot\/ubnkern/kernel \/boot\/ubnkern load_ramdisk=1 prompt_ramdisk=0 ramdisk_size=18000 rw root=\/dev\/ram/g" $1
sed -i "s/kernel \/wubi\/boot\/ubnkern/kernel \/wubi\/boot\/ubnkern load_ramdisk=1 prompt_ramdisk=0 ramdisk_size=18000 rw root=\/dev\/ram/g" $1
