######################################################################
# Automatically generated by qmake (1.08a) Wed Mar 10 15:35:05 2004
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += buttonwidget.h mainwindow.h
SOURCES += buttonwidget.cpp main.cpp
