######################################################################
# Automatically generated by qmake (2.00a) Wed Apr 12 11:28:45 2006
######################################################################

TEMPLATE = app
TARGET += 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
