######################################################################
# Automatically generated by qmake (2.00a) Fri Jan 6 16:44:56 2006
######################################################################

TEMPLATE = app
TARGET += 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += matrix.cpp
