######################################################################
# Automatically generated by qmake (2.00a) Wed Dec 14 11:46:57 2005
######################################################################

TEMPLATE = app
TARGET += 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += renderarea.h stylewidget.h
SOURCES += main.cpp renderarea.cpp stylewidget.cpp
