#!/bin/bash

revno=$(./vcs-revno)

if [ ! -f "release/unetbootin-mac-$revno-unsigned.dmg" ]
then
echo "missing release/unetbootin-mac-$revno-unsigned.dmg"
exit
fi

cd release

7z x unetbootin-mac-$revno-unsigned.dmg

cd ..

if [ ! -d "release/UNetbootin/unetbootin.app" ]
then
echo "missing release/UNetbootin/unetbootin.app"
exit
fi

if [ -d unetbootin-mac-dmg/unetbootin.app ]
then
rm -rf unetbootin-mac-dmg/unetbootin.app
fi

rm -rf release/UNetbootin/unetbootin.app/Contents/Frameworks/Qt*

echo "signing releases/UNetbootin/unetbootin.app/Contents/MacOS/unetbootin"
codesign --deep --entitlements entitlements.xml  --force --verify --verbose --sign "Developer ID Application: Geza Kovacs" --options runtime release/UNetbootin/unetbootin.app/Contents/MacOS/unetbootin
echo "done signing releases/UNetbootin/unetbootin.app/Contents/MacOS/unetbootin"
echo "signing releases/UNetbootin/unetbootin.app"
codesign --deep --entitlements entitlements.xml  --force --verify --verbose --sign "Developer ID Application: Geza Kovacs" --options runtime release/UNetbootin/unetbootin.app
echo "done signing releases/UNetbootin/unetbootin.app"
cp -r unetbootin.app/Contents/Frameworks/Qt* release/UNetbootin/unetbootin.app/Contents/Frameworks/
mv release/UNetbootin/unetbootin.app unetbootin-mac-dmg/unetbootin.app
chmod -R +x unetbootin-mac-dmg/unetbootin.app
rm -rf release/UNetbootin

if [ -f "release/unetbootin-mac-$revno.dmg" ]
then
rm release/unetbootin-mac-$revno.dmg
fi

hdiutil create -volname UNetbootin -srcfolder unetbootin-mac-dmg -ov -format UDZO release/unetbootin-mac-$revno.dmg
rm -rf unetbootin-mac-dmg/unetbootin.app
