#!/bin/sh

mingwb="i586-mingw32msvc"
if [ ! -f "sevnz.dll" ] || [ ! -f "sevnz.exe" ]
then
svloc=$(wget "http://7-zip.org/" -O - | grep --ignore-case "a href=\"http://downloads.sourceforge.net/sevenzip/" | grep -v ".msi" | grep -v "x64" | head --lines 1 | tr "<" "\n" | tr ">" "\n" | tr "\"" "\n" | grep "http://downloads.sourceforge.net/sevenzip/")
wget "$svloc" -O sevenzip.exe
7z e sevenzip.exe 7z.exe 7z.dll
mv 7z.exe sevnz.exe
mv 7z.dll sevnz.dll
fi
rvern="$(bzr version-info | grep revno | sed 's/revno: //')"
make clean
rm Makefile*
rm release/*
lupdate unetbootin.pro
lrelease unetbootin.pro
./qmake-windows
make
$mingwb-strip --strip-all release/unetbootin.exe
mv release/unetbootin.exe release/unetbootin-windows-$rvern.exe
./upx --lzma release/unetbootin-windows-$rvern.exe
./qmake-linux
make
$mingwb-strip --strip-all unetbootin
mv unetbootin release/unetbootin-linux-$rvern
./upx --lzma release/unetbootin-linux-$rvern
printf "UNetbootin Source Revision $rvern\r\nCopyright Geza Kovacs\r\nHomepage at http://unetbootin.sourceforge.net\r\nLicensed under the GNU GPL v2 and above, components from other projects are licensed under their respective licenses\r\nBuild generated on $(date)\r\nDownload using bzr: bzr checkout http://bazaar.launchpad.net/~gezakovacs/unetbootin/devel-new -r$rvern\r\n\r\nBuild instructions at http://unetbootin.wiki.sourceforge.net/compile\r\n\r\nsed -i '/^RESOURCES/d' unetbootin.pro\r\nlupdate unetbootin.pro\r\nlrelease unetbootin.pro\r\nqmake \"DEFINES += NOSTATIC\" \"RESOURCES -= unetbootin.qrc\"\r\nmake\r\n" > README.TXT
zip release/unetbootin-source-$rvern.zip README.TXT $(bzr ls --versioned)
cp unetbootin.pro unetbootin-pro.bak
sed -i '/^RESOURCES/d' unetbootin.pro
echo "DEFINES += NOSTATIC" >> unetbootin.pro
tar -cvzf release/unetbootin-source-$rvern.tar.gz $(bzr ls --versioned | grep '\.cpp$') $(bzr ls --versioned | grep '\.h$') $(bzr ls --versioned | grep '\.ui$') $(bzr ls --versioned | grep '\.h$') $(bzr ls --versioned | grep '\.pro$') $(bzr ls --versioned | grep '\.ts$') debbuild INSTALL README.TXT
mv unetbootin-pro.bak unetbootin.pro

