#!/bin/bash

if [ ! -d release ]
then
mkdir release
fi

qtmacd="$(pwd)/qt4-mac"

#lupdate unetbootin.pro
$qtmacd/bin/lrelease unetbootin.pro
./qmake-mac
make
./fix-unetbootin-frameworkpaths.rb
mv unetbootin.app unetbootin-old.app
ditto --arch i386 unetbootin-old.app unetbootin.app
rm -r unetbootin-old.app

revno=$(./vcs-revno)
zip -r unetbootin-mac-$revno.zip unetbootin.app
mv unetbootin-mac-$revno.zip release

