#!/bin/sh

mingwb="$(ls /usr/ | grep mingw32 | head --lines 1)"
rvern="$(./vcs-revno)"
make clean
rm Makefile*
rm release/*
lupdate-qt4 unetbootin.pro
lrelease-qt4 unetbootin.pro
./qmake-windows "DEFINES += GNEWSENSE" "RESOURCES += unetbootin-gnewsense.qrc"
make
$mingwb-strip --strip-all release/unetbootin.exe
mv release/unetbootin.exe release/unetbootin-gnewsense-windows-$rvern.exe
./upx --lzma release/unetbootin-gnewsense-windows-$rvern.exe
./qmake-linux "DEFINES += GNEWSENSE" "RESOURCES += unetbootin-gnewsense.qrc"
make
$mingwb-strip --strip-all unetbootin
mv unetbootin release/unetbootin-gnewsense-linux-$rvern
./upx --lzma release/unetbootin-gnewsense-linux-$rvern
qmake-qt4 -spec linux-g++-32 "RESOURCES += unetbootin-linux.qrc"

