#!/bin/bash

rvern="$(./vcs-revno)"
qtx11d="$(pwd)/qt5-x11"

if [ ! -d release ]
then
mkdir release
fi

$qtx11d/bin/lrelease unetbootin.pro
./qmake-linux
make
strip --strip-all unetbootin
mv unetbootin release/unetbootin-linux-$rvern.bin
./upx --best --lzma release/unetbootin-linux-$rvern.bin
