#!/bin/bash

if [ "$1" != "" ]
then
cd ../../po
python2.5 /usr/bin/po2ts $1.po -o ../src/unetbootin/unetbootin_$1.ts
cd ../src/unetbootin
exit 0
fi

cd ../../po
for x in $(ls *.po); do python2.5 /usr/bin/po2ts $x -o ../src/unetbootin/unetbootin_$(echo $x | sed "s/po/ts/"); done
cd ../src/unetbootin
