#!/bin/sh

qtwind="$(pwd)/qt4-win"
qtx11d="$(pwd)/qt4-x11"

$qtx11d/bin/qmake -config release -spec $qtx11d/mkspecs/linux-g++-32 "DEFINES += STATICLINUX" "QMAKE_INCDIR_QT = $qtx11d/include" "QMAKE_LIBDIR_QT = $qtx11d/lib" "QMAKE_QMAKE = $qtx11d/bin/qmake" "QMAKE_MOC = $qtx11d/bin/moc" "QMAKE_UIC = $qtx11d/bin/uic" "QMAKE_RCC = $qtx11d/bin/rcc" "RESOURCES += unetbootin-linux.qrc" "$@"
