#!/bin/sh

qtwind="$(pwd)/qt4-win"
qtx11d="$(pwd)/qt4-x11"
mingwb="i586-mingw32msvc"

$qtx11d/bin/qmake -spec $qtwind/mkspecs/win32-g++ "QMAKE_CC = $mingwb-gcc" "QMAKE_CXX = $mingwb-g++" "QMAKE_INCDIR_QT = $qtwind/include" "QMAKE_LIBDIR_QT = $qtwind/lib" "QMAKE_LINK = $mingwb-g++" "QMAKE_COPY_DIR = cp -r" "QMAKE_COPY = cp" "QMAKE_COPY_DIR = cp -r" "QMAKE_MOVE = mv" "QMAKE_DEL_FILE = rm" "QMAKE_CHK_DIR_EXISTS = test -d" "QMAKE_QMAKE = $qtx11d/bin/qmake" "QMAKE_MOC = $qtx11d/bin/moc" "QMAKE_UIC = $qtx11d/bin/uic" "QMAKE_RCC = $qtx11d/bin/rcc" "QMAKE_RC = $mingwb-windres" "RESOURCES += unetbootin-windows.qrc" "QMAKE_LFLAGS += -Wl,-subsystem,windows" "RC_FILE += ubnembed.rc" "$@"
