#!/bin/sh

qtwind="$(pwd)/qt5-win"
mingwb="i686-w64-mingw32"

$qtwind/bin/qmake -config release -spec $qtwind/mkspecs/win32-g++ "DEFINES += STATICWINDOWS" "QMAKE_CC = $mingwb-gcc" "QMAKE_CXX = $mingwb-g++" "QMAKE_INCDIR_QT = $qtwind/include" "QMAKE_LIBDIR_QT = $qtwind/lib" "QMAKE_LINK = $mingwb-g++" "QMAKE_COPY_DIR = cp -r" "QMAKE_COPY = cp" "QMAKE_COPY_DIR = cp -r" "QMAKE_MOVE = mv" "QMAKE_DEL_FILE = rm" "QMAKE_CHK_DIR_EXISTS = test -d" "QMAKE_QMAKE = $qtwind/bin/qmake" "QMAKE_MOC = $qtx11d/bin/moc" "QMAKE_UIC = $qtwind/bin/uic" "QMAKE_RCC = $qtwind/bin/rcc" "QMAKE_RC = $mingwb-windres" "RESOURCES += unetbootin-windows.qrc unetbootin-sevnz.qrc" "QMAKE_LFLAGS += -Wl,-subsystem,windows" "RC_FILE += ubnembed.rc" "$@"
