#!/bin/sh

qtmacd="$(pwd)/qt5-mac"

$qtmacd/bin/qmake -config release -spec $qtmacd/mkspecs/macx-clang "QMAKE_INCDIR_QT = $qtmacd/include" "QMAKE_LIBDIR_QT = $qtmacd/lib" "QMAKE_QMAKE = $qtmacd/bin/qmake" "QMAKE_MOC = $qtmacd/bin/moc" "QMAKE_UIC = $qtmacd/bin/uic" "QMAKE_RCC = $qtmacd/bin/rcc" "CONFIG += x86_64" "$@"
