#!/bin/sh

qtwind="$(pwd)/qt4-win"
qtx11d="$(pwd)/qt4-x11"
mingwb="$(ls /usr/ | grep mingw32 | head --lines 1)"

qmake-qt4 -spec win32-g++ "DEFINES += STATICWINDOWS" "QMAKE_CC = $mingwb-gcc" "QMAKE_CXX = $mingwb-g++" "QMAKE_INCDIR_QT = $qtwind/include" "QMAKE_LIBDIR_QT = $qtwind/lib" "QMAKE_LINK = $mingwb-g++" "QMAKE_COPY_DIR = cp -r" "QMAKE_COPY = cp" "QMAKE_COPY_DIR = cp -r" "QMAKE_MOVE = mv" "QMAKE_DEL_FILE = rm" "QMAKE_CHK_DIR_EXISTS = test -d" "QMAKE_QMAKE = qmake-qt4" "QMAKE_MOC = moc-qt4" "QMAKE_UIC = uic-qt4" "QMAKE_RCC = rcc" "QMAKE_RC = $mingwb-windres" "RESOURCES += unetbootin-windows.qrc unetbootin-sevnz.qrc" "QMAKE_LFLAGS += -Wl,-subsystem,windows" "RC_FILE += ubnembed.rc" "$@"
