#!/bin/sh

qtwind="$(pwd)/qt4-win"
qtx11d="$(pwd)/qt4-x11"
mingwb="i586-mingw32msvc"

$qtx11d/bin/qmake -spec $qtx11d/mkspecs/linux-g++ "QMAKE_INCDIR_QT = $qtx11d/include" "QMAKE_LIBDIR_QT = $qtx11d/lib" "QMAKE_QMAKE = $qtx11d/bin/qmake" "QMAKE_MOC = $qtx11d/bin/moc" "QMAKE_UIC = $qtx11d/bin/uic" "QMAKE_RCC = $qtx11d/bin/rcc" "$@"
