######################################################################
# Automatically generated by qmake (2.01a) Sun Feb 17 20:27:25 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += unetbootin.h
FORMS += unetbootin.ui
SOURCES += main.cpp unetbootin.cpp
