TEMPLATE = app
TARGET =
DEPENDPATH += .
INCLUDEPATH += .
CONFIG += static release
HEADERS += unetbootin.h
FORMS += unetbootin.ui
SOURCES += main.cpp unetbootin.cpp
RESOURCES += unetbootin.qrc
QMAKE_LFLAGS += -Wl,-subsystem,windows
RC_FILE += ubnembed.rc
