#!/bin/bash

vcsname="$(./vcs-name)"

if [ "$vcsname" == "git" ]
then
git ls-files
exit 0
fi

if [ "$vcsname" == "hg" ]
then
hg locate
exit 0
fi

if [ "$vcsname" == "bzr" ]
then
bzr ls --versioned
exit 0
fi

ls
