######################################################################
# Automatically generated by qmake (2.00a) Mon Mar 20 17:17:02 2006
######################################################################

TEMPLATE = app
TARGET += 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += qprocess-simpleexecution.cpp
