######################################################################
# Automatically generated by qmake (1.08a) Tue Jan 4 13:19:41 2005
######################################################################

TEMPLATE = app
CONFIG -= moc
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += buffer.cpp
CONFIG += qt warn_on debug  create_prl link_prl
OBJECTS_DIR=.obj/debug-shared
MOC_DIR=.moc/debug-shared
