######################################################################
# Automatically generated by qmake (2.01a) fr 28. mar 16:53:37 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += layoutitem.h window.h
SOURCES += layoutitem.cpp main.cpp window.cpp

RESOURCES += basicgraphicslayouts.qrc
