######################################################################
# Automatically generated by qmake (2.00a) Wed Apr 5 15:41:54 2006
######################################################################

TEMPLATE = app
TARGET += 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
