#!/bin/sh

if [ -e /boot/grub/menu-bkubn.lst ]; then
mv /boot/grub/menu-bkubn.lst /boot/grub/menu.lst
fi

if [ -e /boot/ubnkern ]
then
rm /boot/ubnkern
fi
if [ -e /boot/ubninit ]
then
rm /boot/ubninit
fi
