######################################################################
# Automatically generated by qmake (2.00a) Wed May 3 15:25:22 2006
######################################################################

TEMPLATE = app
TARGET += 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
