######################################################################
# Automatically generated by qmake (2.01a) Thu Apr 3 11:48:36 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
